// <auto-generated />
using System;
using GestionDocumental.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionDocumental.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentoDbContext))]
    partial class DocumentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionDocumental.Domain.Entities.BitacoraTrazabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescripcionEvento")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaseAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FaseNueva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("GestionDocumental.Domain.Entities.CatalogoCadido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("boolean");

                    b.Property<int>("PlazoConservacionAnios")
                        .HasColumnType("integer");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subserie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Catalogos");
                });

            modelBuilder.Entity("GestionDocumental.Domain.Entities.DocumentoPrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CadidoId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstatusAccion")
                        .HasColumnType("integer");

                    b.Property<int>("FaseCicloVida")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FolioOficial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HashCriptografico")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsUrgente")
                        .HasColumnType("boolean");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RutaRedActual")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CadidoId");

                    b.HasIndex("FolioOficial")
                        .IsUnique();

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("GestionDocumental.Domain.Entities.BitacoraTrazabilidad", b =>
                {
                    b.HasOne("GestionDocumental.Domain.Entities.DocumentoPrincipal", "DocumentoPrincipal")
                        .WithMany("Bitacoras")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoPrincipal");
                });

            modelBuilder.Entity("GestionDocumental.Domain.Entities.DocumentoPrincipal", b =>
                {
                    b.HasOne("GestionDocumental.Domain.Entities.CatalogoCadido", "CatalogoCadido")
                        .WithMany("Documentos")
                        .HasForeignKey("CadidoId");

                    b.Navigation("CatalogoCadido");
                });

            modelBuilder.Entity("GestionDocumental.Domain.Entities.CatalogoCadido", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("GestionDocumental.Domain.Entities.DocumentoPrincipal", b =>
                {
                    b.Navigation("Bitacoras");
                });
#pragma warning restore 612, 618
        }
    }
}
